using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpecialLevel_Board : MonoBehaviour
{
    public ObjectPool_KIM pool;

    public GameObject Brick;

    public float brickSpawnTime;
    public float maxSpawnTime;

    private int spawnCount = 0;

    private void Awake()
    {
        pool = GetComponent<ObjectPool_KIM>();
    }

    private void Start()
    { // ï¿½ï¿½ï¿½Ìµï¿½ ï¿½ï¿½Æ°ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ñ¾î°¬ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿?ï¿½Ê±ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
        // ï¿½ï¿½ï¿½ï¿½Ã¼ï¿½ï¿½ï¿½Ì±ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ù¸ï¿½ ï¿½ï¿½ï¿½Ìµï¿½ Ã³ï¿½ï¿½ Ã³ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        // ï¿½Ý¹ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½Ù¾ï¿½
        Spawn();
        brickSpawnTime = 0;
        maxSpawnTime = 20f;
        spawnCount = 1;
    }

    private void Update()
    { // ï¿½Ã°ï¿½ ï¿½ï¿½ï¿½ï¿½
        brickSpawnTime += Time.deltaTime;

        if (maxSpawnTime <= brickSpawnTime)
        { // 30ï¿½ï¿½? ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ïµï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ brickSpawnTime ï¿½Ê±ï¿½È­
            brickSpawnTime = 0;

            Spawn();
        }
    }

    private void Spawn()
    {// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ®ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ï°ï¿½ ï¿½ï¿½ ï¿½ï¿½Ä¡ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ò±ï¿½?
        if (spawnCount % 2 == 0)
        {
            SpawnPosition(3.4f, 7.6f);
        }
        else
        {
            SpawnPosition(-3.4f, -7.6f);
        }

        spawnCount++;
        // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Ä¡ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ - ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½×·ï¿?ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    }

    private void SpawnPosition(float inSpawnNumber, float inSpawnDirection)
    {
        for (int i = 0; i < 5; i++)
        {
            GameObject newBrick = pool.SpawnFromPool("Brick");
            float x = i % 10 * inSpawnNumber - inSpawnDirection;

            newBrick.transform.position = new Vector2(x, 4f);
        }
    }
}
